<?php

namespace Samane\Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Client' . "\0" . 'id', '' . "\0" . 'Client' . "\0" . 'nom_famille', '' . "\0" . 'Client' . "\0" . 'telephone_abonne', '' . "\0" . 'Client' . "\0" . 'village', '' . "\0" . 'Client' . "\0" . 'abonnements'];
        }

        return ['__isInitialized__', '' . "\0" . 'Client' . "\0" . 'id', '' . "\0" . 'Client' . "\0" . 'nom_famille', '' . "\0" . 'Client' . "\0" . 'telephone_abonne', '' . "\0" . 'Client' . "\0" . 'village', '' . "\0" . 'Client' . "\0" . 'abonnements'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom_famille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom_famille', []);

        return parent::getNom_famille();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom_famille($nom_famille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom_famille', [$nom_famille]);

        return parent::setNom_famille($nom_famille);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone_abonne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone_abonne', []);

        return parent::getTelephone_abonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone_abonne($telephone_abonne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone_abonne', [$telephone_abonne]);

        return parent::setTelephone_abonne($telephone_abonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getVillage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVillage', []);

        return parent::getVillage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVillage($village)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVillage', [$village]);

        return parent::setVillage($village);
    }

    /**
     * {@inheritDoc}
     */
    public function getChef_village()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChef_village', []);

        return parent::getChef_village();
    }

    /**
     * {@inheritDoc}
     */
    public function setChef_village($chef_village)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChef_village', [$chef_village]);

        return parent::setChef_village($chef_village);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbonnements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbonnements', []);

        return parent::getAbonnements();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbonnements($abonnements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbonnements', [$abonnements]);

        return parent::setAbonnements($abonnements);
    }

}
