<?php

namespace Samane\Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consommation extends \Consommation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Consommation' . "\0" . 'id', '' . "\0" . 'Consommation' . "\0" . 'nombre_litre_consomme', '' . "\0" . 'Consommation' . "\0" . 'code_consommation', '' . "\0" . 'Consommation' . "\0" . 'date_consommation', '' . "\0" . 'Consommation' . "\0" . 'prix_litre_eau', '' . "\0" . 'Consommation' . "\0" . 'compteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'Consommation' . "\0" . 'id', '' . "\0" . 'Consommation' . "\0" . 'nombre_litre_consomme', '' . "\0" . 'Consommation' . "\0" . 'code_consommation', '' . "\0" . 'Consommation' . "\0" . 'date_consommation', '' . "\0" . 'Consommation' . "\0" . 'prix_litre_eau', '' . "\0" . 'Consommation' . "\0" . 'compteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Consommation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre_litre_consomme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre_litre_consomme', []);

        return parent::getNombre_litre_consomme();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre_litre_consomme($nombre_litre_consomme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre_litre_consomme', [$nombre_litre_consomme]);

        return parent::setNombre_litre_consomme($nombre_litre_consomme);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode_consommation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode_consommation', []);

        return parent::getCode_consommation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode_consommation($code_consommation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode_consommation', [$code_consommation]);

        return parent::setCode_consommation($code_consommation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteur', []);

        return parent::getCompteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteur($compteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteur', [$compteur]);

        return parent::setCompteur($compteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate_consommation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate_consommation', []);

        return parent::getDate_consommation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate_consommation($date_consommation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate_consommation', [$date_consommation]);

        return parent::setDate_consommation($date_consommation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix_litre_eau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix_litre_eau', []);

        return parent::getPrix_litre_eau();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix_litre_eau($prix_litre_eau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix_litre_eau', [$prix_litre_eau]);

        return parent::setPrix_litre_eau($prix_litre_eau);
    }

}
